### ISSUE TITLE
Can't play bags with `v9` metadata

### ISSUE THREAD

**Issue by Fixit-Davide** [ros-visualization/rqt_bag#146]
Since https://github.com/ros2/rosbag2/pull/1476 there may be an incompatibility with the current capabilities of this RQT plugin.

I get this error when trying to load a bag to play:
```
Loading `bag/file/path` failed due to: Exception on parsing info file: yaml-cpp: error at line 11, column 11: bad conversion
```

CC @roncapat

**Comment by roncapat** [comment]
@MichaelOrlov I tested again and it is something happening in:
```
            self.reader = rosbag2_py.SequentialReader()
            self.reader.open(
                rosbag2_py.StorageOptions(uri=bag_path), rosbag2_py.ConverterOptions())
```
so related to rosbag2. Any clue?

Line 11 column 11 is:
```yaml
rosbag2_bagfile_information:
  version: 9
  storage_identifier: sqlite3
  duration:
    nanoseconds: 352757433264
  starting_time:
    nanoseconds_since_epoch: 1703179683403182547
  message_count: 161592
  topics_with_message_count:
    - topic_metadata:
        name: /zed_camera/odom
        type: nav_msgs/msg/Odometry
        serialization_format: cdr
        offered_qos_profiles:
          - history: unknown    # THIS ONE
            depth: 0
            reliability: reliable
            durability: volatile
            deadline:
              sec: 9223372036
              nsec: 854775807
            lifespan:
              sec: 9223372036
              nsec: 854775807
            liveliness: automatic
            liveliness_lease_duration:
              sec: 9223372036
              nsec: 854775807
            avoid_ros_namespace_conventions: false
        type_description_hash: RIHS01_3cc97dc7fb7502f8714462c526d369e35b603cfc34d946e3f2eda2766dfec6e0
      message_count: 5939
```

I think there is an issue in YAML compatibility of the `metadata.yaml`... why that line starts as a list item?
